arquivo = open("palavras.txt", "w")
arquivo.write("banana\n")
arquivo.write("maracuja\n")
arquivo.write("abacaxi\n")
arquivo.write("goiaba\n")
arquivo.write("morango\n")
arquivo.write("limao\n")
arquivo.write("amora\n")
arquivo.write("acerola\n")
arquivo.close()
